### ISSUE TITLE
Setting JSX children is currently not implemented.

### ISSUE THREAD

**Issue by Alloyed** [dsherret/ts-simple-ast#1232] opened 2021-12-17 17:03 UTC
**Describe the bug**

Version: 13.0.2

So I'd like to write a few transformations on JSX elements, and when testing some simple examples I found a NYI error.

**To Reproduce**

Here is the transformation this sample is targeting:
```ts
// from
import React from 'react';

export function TestComponent(): JSX.Element {
  return <div id="test"></div>
}

// to
import React from 'react';

export function TestComponent(): JSX.Element {
  return <div id="test"> <div id="inner" /> </div>
}
```

```ts
import { Project, SyntaxKind, StructureKind } from "ts-morph";
function main() {
    const project = new Project();
    const sourceFile = project
        .getSourceFiles()
        .filter((f) => /sample\.tsx/.test(f.getFilePath().toString()))[0]!;

    sourceFile
        .getFunction('TestComponent')
        ?.getDescendantsOfKind(SyntaxKind.JsxElement)
        .forEach((expr) => {
            const structure = expr.getStructure();

            structure.children ??= [];
            structure.children.push({
                kind: StructureKind.JsxSelfClosingElement,
                name: 'div',
                attributes: [
                    {
                        kind: StructureKind.JsxAttribute,
                        name: 'id',
                        initializer: '"inner"',
                    },
                ],
            });
            expr.set(structure);
        });

    project.saveSync();
}
main();
```
**Actual behavior**
`Uncaught Error: Setting JSX children is currently not implemented. Please open an issue if you need this.`

**Expected behavior**
an implementation for `children` in JSXElement's `set(structure)`.

You'll also notice in the sample code that our initial JSXElement is _not_ a JSXSelfClosingElement. In situations where I'd want to add a node to a self closing element, or remove all nodes from a normal element, I would need to create a new structure of the opposite kind and copy over each property manually. Since this seems like a fairly common thing to do, it'd be nice if the structure API had methods to handle the busywork for me.

**Comment by dsherret** [comment] 2021-12-17 17:04
See #240. It's hard to do and I haven't had time.

**Comment by dsherret** [comment] 2022-01-22 20:14
Closing this as a duplicate of #240.

**Closed as completed by dsherret** 2022-01-22 20:14 UTC
Labels: duplicate
