### ISSUE TITLE
OrganizeImports breaks sourcefile filtering

### ISSUE THREAD

**Issue by marikaner** [dsherret/ts-simple-ast#517] opened 2018-12-21 16:05 UTC
We use `ts-simple-ast` for a code generator. I just recently decided to beautify the generated code by cleaning up the imports (among others). Weirdly this changes what sources belong to the project:

This is a minimal example:
```ts
import path from 'path';
import Project, { ts } from 'ts-simple-ast';

console.log(ts.version); // 3.2.2

const project = new Project({
    tsConfigFilePath: path.resolve(__dirname, './tsconfig.json'),
    addFilesFromTsConfig: false,
    skipFileDependencyResolution: true
});

const file = project.createSourceFile('out/testFile.ts', '', {
    overwrite: true
});

console.log('#files before:', project.getSourceFiles().length); // #files before: 1

file.organizeImports();

console.log('#files after:', project.getSourceFiles().length); // #files after: 6

project.save();

```

I would expect the number of files not to change.

Also: we ❤️`ts-simple-ast`

**Comment by dsherret** [comment] 2019-01-06 23:13
Hey @marikaner, this is because organizing the imports will cause file dependency resolution... so the files will be added to the project.

Also, sorry for the long response, but it was the holidays and I've been thinking about what can be done here. I think the expected behaviour you're describing makes a lot of sense, so I've opened #522 and that should resolve this issue once implemented. Let me know your thoughts.

**Comment by dsherret** [comment] 2019-01-10 02:59
This will be resolved in version 21 via #522 and #523.

**Closed by dsherret** 2019-01-10 02:59 UTC

**Comment by marikaner** [comment] 2019-01-10 08:48
Thank you for fixing it so quickly! I did not have time to try it out yet, though.

**Comment by dsherret** [comment] 2019-01-10 14:02
I haven't released it yet. I still have to write up the list of breaking changes and then publish it (will do by sunday night).
