### ISSUE TITLE
PropertyAssignmentStructure name property does not allow for quoted strings

### ISSUE THREAD

**Issue by nadavsinai** [dsherret/ts-simple-ast#344] opened 2018-06-09 10:34 UTC
Hey,

First of all thank you for this wonderful library. I find it very useful.

I was using ObjectLiteralExpression.addPropertyAssignment and tried to use a name wrapped in double quotes eg '"options"' (which is legal in JavaScript and allows for things such as reserved name properties such as '"class"' and dash joint words such as  '"some-others"', as well as necessary point to make an object valid JSON)
this error is thrown : 
````
Error: Cannot read property 'kind' of undefined
-- Details --
Path: E:/Data/showWS/ribbon.initialstate.ph_modfiled.ts
Text: "...\t\t\t\"tooltip\": \"Lesions\",\n\t\t\t\t\t\t\"text\": \"Lesions\",\n\t\t\t\t\t\t\"clientActionOnly\": true\n\t\t\t\t\t},\n\t\t\t\t\t\n\t\t\
t\t\t\n\t\t\t\t\t\"children\": [],\n                    \"options\": {\n                        {\n                                                \"s
howIcon\": true,\n                                                \"showText\": false\n                                            }\n
    }\n                },\n\n\t\t\t]\n\t\t},\n\t\t{\n\t\t\t\"type\": \"TabsContainerModel\",\n\t\t\t\"toolID\": \"ribbon.control\",\n\t\t\t\"elementMo
del\": {..."
    at InvalidOperationError.BaseError [as constructor] (E:\Data\showWS\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
    at new InvalidOperationError (E:\Data\showWS\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:8:28)
    at Object.doManipulation (E:\Data\showWS\node_modules\ts-simple-ast\dist\manipulation\manipulations\doManipulation.js:12:15)
    at insertIntoParentTextRange (E:\Data\showWS\node_modules\ts-simple-ast\dist\manipulation\manipulations\insertion.js:16:22)
    at Object.insertIntoCommaSeparatedNodes (E:\Data\showWS\node_modules\ts-simple-ast\dist\manipulation\manipulations\insertion.js:53:9)
    at ObjectLiteralExpression._insertProperty (E:\Data\showWS\node_modules\ts-simple-ast\dist\compiler\expression\object\ObjectLiteralExpression.js:2
39:24)
    at ObjectLiteralExpression.insertPropertyAssignments (E:\Data\showWS\node_modules\ts-simple-ast\dist\compiler\expression\object\ObjectLiteralExpre
ssion.js:69:21)
    at ObjectLiteralExpression.addPropertyAssignments (E:\Data\showWS\node_modules\ts-simple-ast\dist\compiler\expression\object\ObjectLiteralExpressi
on.js:52:21)
    at ObjectLiteralExpression.addPropertyAssignment (E:\Data\showWS\node_modules\ts-simple-ast\dist\compiler\expression\object\ObjectLiteralExpressio
n.js:45:21)
    at visitTSNode (E:\Data\showWS\fix-external-options.js:78:17)
````

if I remove the quotes (this time it was only for consistency with other properties on that object, which is really a JSON)
it runs OK

**Comment by dsherret** [comment] 2018-06-09 14:44
Hey @nadavsinai, there must be some kind of bug here, but I think it's probably the same as #334. I just committed some tests that pass when using single and double quotes for the name.

I never received word back in #334 about how to reproduce. Would you be able to provide a simple example that reproduces the bug? Thanks!

**Comment by dsherret** [comment] 2018-07-02 00:36
I'm closing this as a duplicate of #334. I still don't know what causes this issue because I'm awaiting feedback on that issue.

**Closed by dsherret** 2018-07-02 00:36 UTC
