### ISSUE TITLE
TypeGuards.hasName throws 

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-simple-ast#368] opened 2018-07-17 10:33 UTC
and is calling getName which in some situations could have negative impact on performance - typeguards should be lightweight:
```ts
xit("should never throw", () => { // is throwing!
    const { sourceFile } = getInfoFromText(`export default function(){}`);
    sourceFile.getDescendants().forEach(node => {
        const nodeLabel = node.getKindName() + "-" + node.getText();
        expect(() => TypeGuards.hasName(node), nodeLabel).not.to.throw();
    });
});
```

**Comment by dsherret** [comment] 2018-07-17 13:16
Hi @cancerberoSgx, thanks for reporting this! The problem is that `FunctionDeclaration` is a `NamedNode` and not a `NameableNode`. I opened #368 and will do that one soon.

Also, it's calling `.getName()` to check if it has a name.

Anyway, this will be fixed in #368 so I'm going to close this issue and fix the root of the problem there.

**Closed by dsherret** 2018-07-17 13:16 UTC
Labels: bug

**Comment by lazarljubenovic** [comment] 2018-07-17 15:04
@dsherret I legit thought I was drunk for a moment. (You meant to link to #369, just re-stating it for completeness :smile:)

**Comment by dsherret** [comment] 2018-07-17 15:09
@lazarljubenovic hah! Yeah, definitely meant #369. That was not supposed to be a self-referential supersession... though I wouldn't mind closing all issues that way :P

Thanks!
