### ISSUE TITLE
Duplicate method declarations exists in the emitted .d.ts file of this JS file

### ISSUE THREAD

**Issue by likuner** [dsherret/ts-simple-ast#1280] opened 2022-05-21 15:20 UTC
**Describe the bug**

Version: 14.0.0

duplicate code exists in the .d.ts declaration file generated by ts-morph from **.js** file.

**To Reproduce**
``` javascript
// .js
export default {
    methods: {
        handleScroll() {}
    }
};
```
```typescript
// .d.ts
// handleScroll is duplicate
declare namespace _default {
    namespace methods {
        function handleScroll(): void;
        function handleScroll(): void;
    }
}
export default _default;
```

**Expected behavior**
no duplicate code

**Comment by dsherret** [comment] 2022-05-21 15:23
@likuner could you fill in this part of the issue template to show how you reproduced the problem?

```ts
import { Project } from "ts-morph";

const project = new Project();
const sourceFile = project.createSourceFile("test.js", `export default {
    methods: {
        handleScroll() {}
    }
};`);

// reproduce the problem here
```

**Comment by likuner** [comment] 2022-05-21 15:36
> @likuner could you fill in this part of the issue template to show how you reproduced the problem?
> 
> ```ts
> import { Project } from "ts-morph";
> 
> const project = new Project();
> const sourceFile = project.createSourceFile("test.js", `export default {
>     methods: {
>         handleScroll() {}
>     }
> };`);
> 
> // reproduce the problem here
> ```

```javascript
// reproduce the problem here
const { Project } = require("ts-morph");

const project = new Project({
  compilerOptions: {
      declaration: true,
      emitDeclarationOnly: true,
      noEmitOnError: true,
      allowJs: true,
      outDir: 'comp_types'
  },
  skipAddingFilesFromTsConfig: true
})

const sourceFile = project.createSourceFile("test.js", `export default {
  methods: {
      handleScroll() {}
  }
};`);

project.emit();
```

**Comment by dsherret** [comment] 2022-05-21 15:39
Thanks! I can reproduce it. Most likely it is a bug in the ts compiler.

**Comment by likuner** [comment] 2022-05-21 15:42
> Thanks! I can reproduce it. Most likely it is a bug in the ts compiler.

OK, please let me know after the problem is solved, I need it urgently, Thanks!

**Comment by dsherret** [comment] 2022-05-21 15:54
@likuner well I won't be able to fix it because I don't have time and it's a bug with the TypeScript compiler. If you need this fixed then you can look into fixing this bug I opened in TS's repo: https://github.com/microsoft/TypeScript/issues/49200

**Comment by dsherret** [comment] 2024-03-09 20:53
I think this one is fixed now.

**Closed as completed by dsherret** 2024-03-09 20:53 UTC
Labels: bug, compiler api
