### ISSUE TITLE
Issue With Namespaces?

### ISSUE THREAD

**Issue by sfrooster** [dsherret/ts-simple-ast#35] opened 2017-06-19 01:12 UTC
SourceFile.getClasses() does not return classes which are inside a namespace.  Do I need to do something to access the namespaces?  I can get them with getNamespaces, but then I don't seem to be able to access the classes within that namespace...

**Comment by dsherret** [comment] 2017-06-19 01:18
@sfrooster since it's a tree, you will have to get the namespace first then get the class within the namespace. So something like this:

```typescript
const sourceFile = ...
sourceFile.getNamespace("NamespaceName")!.getClasses(); // or whatever way to get the namespace
```

Perhaps an easy way could be added for getting all classes including ones within namespaces and functions too.

**Comment by sfrooster** [comment] 2017-06-19 01:34
Yep, it was the same as the previous issue.  getClasses didn't appear at first but eventually, when I went back, it did appear.  I'm going to close the previous issue - it's probably a vscode issue.

I'm getting "Error: A child syntax list was expected." when looking for classes on that namespace.  That namespace doesn't have any classes but does have another module.  Anyway, I'll play with it a bit more and probably end-up closing this one too.

FYI - your lib is *WAY* easier to use than so far than the straight compiler api!

**Comment by dsherret** [comment] 2017-06-19 01:47
Do you have some code that reproduces that error? That definitely shouldn't happen. It might be something I didn't take into account.

Thanks! I know... the compiler api is very difficult to use. Sometimes a simple function in this library will be a ton of code using the compiler api.

**Comment by sfrooster** [comment] 2017-06-19 01:57
I'm just starting to play with you lib so I can figure out how best to use it so the code I'm currently running looks like:
`import Ast from "ts-simple-ast";
import * as ts from "typescript";

const ast = new Ast({
    tsConfigFilePath: "tsconfig.json"
});

ast.addSourceFiles("msgs/**/*{.d.ts,.ts}");

ast.getSourceFiles().forEach(sf => {
    console.log(sf.getFilePath());

    let nscc: number[] = [];
    let ns = sf.getNamespaces();
    ns.forEach(n => {
        nscc.push(n.getClasses().length);
    });
    let classes = sf.getClasses();
    let ifaces = sf.getInterfaces();

    console.log(`c: ${classes.length}, i: ${ifaces.length}, n: ${nscc}`);
    console.log("=================");
});`

An example of a source file it's having an issue with is:
`export namespace Demo.UserProfiles.Commands {
    export class CreateUserProfile extends Message {
        constructor();
        constructor(Email: string, FirstName: string, LastName: string, SecurityToken: string);
        constructor(public Email: string = "", public FirstName?: string, public LastName?: string, public SecurityToken?: string) {
            super();
        }
    }
}`

Specifically this line "nscc.push(n.getClasses().length);" is choking on the UserProfiles piece of "export namespace Demo.UserProfiles.Commands".

I hope that helps!

**Comment by dsherret** [comment] 2017-06-19 02:13
Yes, it does! Thank you very much!

So I never thought about namespaces that have dots in the name. What the AST does is this:

```
ModuleDeclaration - Demo
  - ModuleDeclaration - UserProfiles
    - ModuleDeclaration - Commands
      - ModuleBlock
        -SyntaxList  
          - ClassDeclaration
````

If you do `.getName()` on the namespace you'll see it just return `Demo`. An ugly work around is to do:

```typescript
const innerNamespace = ns.getFirstChildByKindOrThrow(ts.SyntaxKind.ModuleDeclaration)
    .getFirstChildByKindOrThrow(ts.SyntaxKind.ModuleDeclaration) as NamespaceDeclaration;
nscc.push(innerNamespace.getClasses().length);
```

I'm working on a fix right now though, but I'll also need to fix what `.getName()` returns.

**Comment by sfrooster** [comment] 2017-06-19 02:24
I think I can work with that until you get a fix in.  I'll need to tweak it to handle variable length dot-separated namespaces, but I'm sure that's doable.

In reality, I think your code is mostly right.  When tsc compiles that it treats it as three nested modules or whatever:
`var Demo;
(function (Demo) {
    var UserProfiles;
    (function (UserProfiles) {
        var Commands;
        (function (Commands) {
            var CreateUserProfile = (function (_super) {`

So the name of the first Node is actually "Demo".  getClasses in that case should just return an empty list but then getModules / getNamespaces (I'm not sure which is appropriate) should return "UserProfiles" - don't you think?

I'll defer to you but that seems correct to me.

**Comment by dsherret** [comment] 2017-06-19 02:57
Fixed in 0.28.2.

In this case, I think it makes sense to return the classes/interfaces/functions/namespaces/etc within the `ModuleBlock` for every `ModuleDeclaration` in the tree. I think it's very unlikely that someone would want to do `ns.getNamespaces()[0].getNamespaces()[0].getClasses()` just in order to get the classes within the block and that would be annoying. If someone really wants to traverse down the tree on their own, they can always do what I mentioned in my last post, by doing `.getFirstChildByKind(ts.SyntaxKind.ModuleDeclaration)`.

I'm going to think about what to do with `.getName()` tomorrow. I think you're right that it should return `Demo` because that's what's on the `.name` property, but I may want to just make the common case the default (fully qualified name?) and then allow people to specify what kind of name they want if not.

**Comment by sfrooster** [comment] 2017-06-19 03:01
I have switched over to java land briefly but will be back in TS world a little later and I'll give it a try.

**Comment by sfrooster** [comment] 2017-06-19 08:30
I'm not sure exactly which direction you're headed in but I did play around
with this some more this evening.  I was ultimately able to get the correct
result, but it was mixed in with misleading results.  This probably gets to
your
getName question because getClasses was returning a class buried three
levels deep when I called it at each level.

Unless getClasses called at a top level can indicate the correct level for
each returned class, I'd think it would be better if it was only returned
after the correct level.

My .02

On Jun 18, 2017 7:57 PM, "David Sherret" <notifications@github.com> wrote:

Fixed in 0.28.2.

In this case, I think it makes sense to return the
classes/interfaces/functions/namespaces/etc within the ModuleBlock for
every ModuleDeclaration in the tree. I think it's very unlikely that
someone would want to do ns.getNamespaces()[0].
getNamespaces()[0].getClasses() just in order to get the classes within the
block and that would be annoying. If someone really wants to traverse down
the tree on their own, they can always do what I mentioned in my last post,
by doing .getFirstChildByKind(ts.SyntaxKind.ModuleDeclaration).

I'm going to think about what to do with .getName() tomorrow. I think
you're right that it should return Demo because that's what's on the .name
property, but I may want to just make the common case the default (fully
qualified name?) and then allow people to specify what kind of name they
want if not.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dsherret/ts-simple-ast/issues/35#issuecomment-309327159>,
or mute the thread

**Comment by dsherret** [comment] 2017-06-20 01:19
Given the following code:

```typescript
export namespace Demo.UserProfiles.Commands {
    export class Class1 {
    }

    export namespace InnerNamespace {
        export class Class2 {
        }
    }
}

export namespace Demo.UserProfiles {
    export class Class3 {
    }
}
```

**Result of getClasses(), getNamespaces(), etc...**

I'm sure most people would expect it to behave the following way (as you did when you initially tried it out and I would have thought would work myself):

```typescript
const namespaces = sourceFile.getNamespaces();
namespaces.length; // 1

// first namespace
const ns1 = namespaces[0];
ns1.getClasses();      // 1, Class1
const ns1Inner = ns1.getNamespaces()[0];
ns1Inner.getClasses(); // 1, Class2

// second namespace
const ns2 = namespaces[1];
ns2.getClasses();      // 1, Class3
```

I believe that's now the current behaviour. I usually try to mirror the AST exactly in most cases, but I view these `.getClasses()` as helper methods that help get things more easily. In this case, `.getClasses()` can be viewed as getting all the classes within the braces.

**Dot Notation Names**

I've been thinking about how the name should work on namespaces. I'm thinking of replacing the current name methods:

```typescript
// current
getNameNode(): Identifier;
getName(): string;
rename(newName: string): this;

// final - renamed to somewhat reflect that these are different nodes
getNameNodes(): Identifier[];
getFullName(): string;
setFullName(newFullName: string): this;
```

So in the example above the following code would happen:

```typescript
ns1.getFullName(); // "Demo.UserProfiles.Commands"
ns1.getNameNodes()[0].getText(); // "Demo"
ns1.getNameNodes()[0].rename("NewDemo"); // renames usages of "Demo" to "NewDemo"
ns1.setFullName("Demo.UserProfiles.New.Commands"); // inserts "New"
```

Overall, with a statement like "namespace Demo.UserProfiles.Commands {}", I would rather have to explain to a couple of people why it's the way I outlined above than to explain to everyone about the underlying AST structure. Maybe I'm completely wrong about this though... I'm still thinking about it.

What are your thoughts?

**Comment by sfrooster** [comment] 2017-06-20 05:13
I've updated to 0.30.0 and been playing around with it.  What it really comes down to is being able to properly work with namespaces/modules.  As far as I can tell getClasses does return all the classes encapsulated by the given namespace / module.

It also seems like you can find a class's proper namespace if you start with the class and work your way up through getParent - I've been able to do that manually but it remains to be seen how easily I can automate that (probably not too bad).

The difficult part is trying to take a top-down namespace approach and be accurate in identifying where you are in the namespace.

Given code like:

```typescript
export namespace Demo.UserProfiles.Commands {
    export class CreateUserProfile extends Message {
        public static readonly Version: string = "1.0";   // version to pass to EDAProperties
        public static readonly TypeID = "OT.Messages.Demo.UserProfiles.Commands.CreateUserProfile";

        public get Key(): number[] {
            return stringToByteArray(this.Email!);
        }

        constructor();
        constructor(Email: string, FirstName: string, LastName: string, SecurityToken: string);
        constructor(public Email: string = "", public FirstName?: string, public LastName?: string, public SecurityToken?: string) {
            super();
        }
    }

    export namespace Nested {
        export class CreateUserProfile2 {
            public x: number = 0;
        }
    }
}
```

You need the two of these
```typescript
let nsc = ns.getNamespaces();
let cok = ns.getChildrenOfKind<NamespaceDeclaration>(ts.SyntaxKind.ModuleDeclaration);
```
to scan through the entire "namespace" and if you process the entire tree recursively, what you'll find is that "Nested" is identified as a sub namespace/module of each part of the original namespace so "Demo", "UserProfiles", and "Commands" when in reality it should only be a sub namespace/module of "Commands".

Here's my messed-up code:

```typescript
import Ast from "ts-simple-ast";
import { ClassDeclaration, NamespaceDeclaration, Node } from "ts-simple-ast";
import * as ts from "typescript";
import * as _ from "lodash";
import * as util from "util";

const ast = new Ast({
    tsConfigFilePath: "tsconfig.json"
});

ast.addSourceFiles("msgs/**/*{.d.ts,.ts}");

let classNames: string[] = [];

ast.getSourceFiles().forEach((sf, idx) => {
    if (idx === 0) {
        console.log(sf.getFilePath());
        processNS2(sf.getNamespaces());
    }
});

function processNS2(nss: NamespaceDeclaration[], level: number = 0) {
    let prefix = _.padStart("", level * 4, " ");

    nss.forEach(ns => {
        classNames.push(...ns.getClasses().map(c => c.getName()));
        classNames = _.uniq(classNames).sort();
        console.log(prefix, `CLASSES: ${classNames.join(", ")}`);

        console.log(prefix, `NS: ${ns.getName()}`);
        ns.getClasses().forEach(c => {
            console.log(prefix, `C: ${c.getName()}`);
        });

        let nsc = ns.getNamespaces();
        let cok = ns.getChildrenOfKind<NamespaceDeclaration>(ts.SyntaxKind.ModuleDeclaration);

        console.log(prefix, `NSC: ${nsc.map(nsd => nsd.getName()).join(", ")}`);
        processNS2(nsc, level + 1);
        console.log(prefix, `COK: ${cok.map(nsd => nsd.getName()).join(", ")}`);
        processNS2(cok, level + 1);

        console.log(prefix, "===============");
    });
}
```

**Comment by dsherret** [comment] 2017-06-24 21:03
I've changed the behaviour a little here in 0.35.0. Now the following will happen:

```typescript
export namespace Demo.UserProfiles.Commands {
    export class Class1 {
    }
}
```

```typescript
const namespaceDec = sourceFile.getNamespaces()[0];
namespaceDec.getName(); // returns: Demo.UserProfiles.Commands
namespaceDec.setName("Demo.User.Other"); // would set the name to that... not implemented yet
namespaceDec.getNameIdentifiers(); // returns the identifiers for Demo, UserProfiles, and Commands
cons classDec = namespaceDec.getClasses()[0]; // returns: Class1 ClassDeclaration

classDec.getParentNamespace() === namesaceDec;
```

I believe in this case it is fine to hide some complexity here to support the simplest and what I believe to be the expected behaviour to someone who has never navigated the AST. For a user who really wants to go down through the AST here they could do that if they wanted, but I don't see the point.

**Comment by dsherret** [comment] 2017-07-01 16:10
I'm going to close this for now. The only part that's not implemented is calling setName when dot notation is used currently or setting it to use dot notation. Let me know if there's anything I missed or if this doesn't address the issue.

**Closed by dsherret** 2017-07-01 16:10 UTC
Labels: bug
